# Generated by Django 5.1.1 on 2024-09-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('activo', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], default=True)),
                ('horario', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('C', 'Completo'), ('O', 'Otros')], default='O', max_length=1)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('campaña', models.CharField(choices=[('BSL', 'BSL'), ('JUGUETES', 'Juguetes'), ('VIVAMOS', 'Vivamos Circular'), ('NINGUNO', 'Ninguno')], default='NINGUNO', max_length=8)),
            ],
        ),
    ]
