# Generated by Django 5.1.1 on 2024-09-26 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuestosDelDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('C', 'Completo')], max_length=1)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mesa_1_empleados', models.ManyToManyField(blank=True, related_name='mesa_1', to='myapp.empleado')),
                ('mesa_1_tareas', models.ManyToManyField(blank=True, related_name='mesa_1_tareas', to='myapp.tarea')),
                ('mesa_2_empleados', models.ManyToManyField(blank=True, related_name='mesa_2', to='myapp.empleado')),
                ('mesa_2_tareas', models.ManyToManyField(blank=True, related_name='mesa_2_tareas', to='myapp.tarea')),
                ('mesa_3_empleados', models.ManyToManyField(blank=True, related_name='mesa_3', to='myapp.empleado')),
                ('mesa_3_tareas', models.ManyToManyField(blank=True, related_name='mesa_3_tareas', to='myapp.tarea')),
                ('mesa_4_empleados', models.ManyToManyField(blank=True, related_name='mesa_4', to='myapp.empleado')),
                ('mesa_4_tareas', models.ManyToManyField(blank=True, related_name='mesa_4_tareas', to='myapp.tarea')),
            ],
        ),
    ]
