# Generated by Django 5.1.1 on 2024-09-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_puestosdeldia_creado_por'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puestosdeldia',
            unique_together={('fecha', 'horario')},
        ),
    ]
